name: pythagorean-triplet
version: 1.0.0.4

dependencies:
  - base

library:
  exposed-modules: Triplet
  source-dirs: src
  ghc-options:
    -Wall
    -eventlog
    -O2
    -threaded
    -rtsopts
  dependencies:
    - parallel
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pythagorean-triplet
      - hspec
